# Generated by Django 2.0.2 on 2018-02-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0004_auto_20180128_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='is_done',
        ),
        migrations.AddField(
            model_name='sprint',
            name='state',
            field=models.IntegerField(default=1),
        ),
    ]
