# Generated by Django 2.0.1 on 2018-01-28 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backlog', '0003_auto_20180127_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
